/**
 * Author: Professor Krasso
 * Date: 7 August 2024
 * File: app.js
 * Description: Application setup. Autogenerated using Express generator.
 */

// require statements
const express = require('express');
const cookieParser = require('cookie-parser');
const logger = require('morgan');
const mongoose = require('mongoose');
const { notFoundHandler, errorHandler } = require('./error-handler');

// Route imports
const indexRouter = require('./routes/index');
const inventoryRouter = require('./routes/inventory');
const supplierRouter = require('./routes/supplier');
const cors = require('cors');


// Variable declaration for the express app
let app = express();

// Database connection logic (exported to allow testing)
const connectionString = process.env.MONGO_URI || 'mongodb+srv://apollo:s3cretApollo@cluster0.4auoir7.mongodb.net/?appName=Cluster0';

const dbName = process.env.DB_NAME || 'Apollo'; // Database name

/*
const connectionString = process.env.MONGO_URI;
const dbName = process.env.DB_NAME || 'Apollo';
*/

// Function to connect to the database
async function connectToDatabase(){
  try{
    await mongoose.connect(connectionString, {
      dbName: dbName,
    });
    console.log(`Connection to the '${dbName}' database was successful`);
  }catch(err){
    console.error(`MongoDB connection error: ${err}`);
  }
}

// CORS configuration
/*
app.use((req, res, next) => {
  res.setHeader('Access-Control-Allow-Origin', '*'); // This allows all origins
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, PATCH, DELETE, OPTIONS'); // Allowed request methods
  res.setHeader('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept'); // Allowed headers
  next();
});
*/

app.use(cors({
  origin: [
    'http://localhost:4200',
    'https://apollo-client-kfcc.onrender.com'
  ],
  methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'],
  allowedHeaders: ['Content-Type', 'Authorization'],
  credentials: true
}));

// Handle preflight requests
app.options('*', (req, res) => {
  res.sendStatus(200);
});


// Express app configuration
app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());

// Routing configuration
app.use('/api', indexRouter);
app.use('/api/inventory', inventoryRouter);
app.use('/api/supplier', supplierRouter);


// Use the error handling middleware
app.use(notFoundHandler);
app.use(errorHandler);

// Export the app and the database connection function
module.exports = app;
app.connectToDatabase = connectToDatabase;
